function alignedFrames = importalignedFrames(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MOUSE1ALUMINUM3 = importalignedFrames(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  alignedFrames = importalignedFrames(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  mouse1aluminum3 = importalignedFrames("/home/ben/lampllab/Ben/Data/Objects 2023/Videos2use/Raw sound/mouse1_aluminum_2.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jan-2024 10:21:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3"];
opts.SelectedVariableNames = "VarName3";
opts.VariableTypes = ["string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");

% Import the data
alignedFrames = readtable(filename, opts);

%% Convert to output type
alignedFrames = table2array(alignedFrames);
end