function events3 = importDate(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EVENTS3 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a cell array.
%
%  EVENTS3 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  events3 = importfile("/home/ben/Downloads/events2224.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Feb-2024 08:53:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "T1552088945152", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"];
opts.SelectedVariableNames = "T1552088945152";
opts.VariableTypes = ["string", "char", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "T1552088945152", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "T1552088945152", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"], "EmptyFieldRule", "auto");

% Import the data
events3 = readtable(filename, opts);

%% Convert to output type
events3 = table2cell(events3);
numIdx = cellfun(@(x) ~isnan(str2double(x)), events3);
events3(numIdx) = cellfun(@(x) {str2double(x)}, events3(numIdx));
end